services:
  playwright-test:
    image: todos-pw-test
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npx playwright test --project=chromium
    volumes:
      - ./playwright-report/:/app/playwright-report
      - ./test-results/:/app/test-results
